taksi_server/config/routes.rb
Rails.application.routes.draw do
  match '*all' => 'application#cors_preflight', via: :options
  post "/bookings", :to => "bookings#create"
  post "/bookings/cancel", :to => "bookings#update"
  post "/drivers/request", :to=>"drivers#show"
  post "/drivers/answer", :to=>"drivers#answer"
  post "/drivers/accepted", :to=>"drivers#index"
  post "/drivers/requestStatus", :to=>"drivers#requestStatus"
  post "/drivers/updateStatus", :to=>"drivers#updateStatus"
  post "/drivers/location", :to=>"drivers#location"
  post "/drivers/invoice", :to=>"drivers#invoice"
  post "/drivers/invoicePayment", :to=>"drivers#invoicePay"
  post "/login", :to=>"drivers#login"

end

taksi_server/app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :drivers
  validates :location, presence:true
end

taksi_server/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @booking = Booking.all
  end

  def create
    booking = Booking.new(
        :location => "{'lat' : #{params[:latitude]},'lng' : #{params[:longitude]}}",
        :status => 'pending',
        :fee=> params[:fee],
        :destination => params[:destination],
        :paid=>false
    )
    booking.save!
    session[:client]=booking.id
    #    bookingId=assignToDriver(params[:latitude], params[:longitude])
    #BookingsAsyncJob.new.async.perform("Your booking has been confirmed", 0, 0)
    BookingsAsyncJob.new.async.assignToDriver(booking, params[:latitude], params[:longitude])
    #BookingsAsyncJob.new.async.perform("Your booking has been confirmed", 0, 0)
    render :json => {
           :message => "#{params[:fee]}",
           :bookingId=>booking.id
    }, :status => :created
  end

  def edit
    @booking = Booking.find params[:bookingId]
  end

  def show
    @booking = Booking.find params[:id]
  end

  def update
    @booking = Booking.find params[:bookingId]
    @booking.status="canceled"
    @booking.save!
    driverUpdate(@booking.driver_id,"Available",0)
    Pusher.trigger('drivers', 'async_notification', {:canceled=> true,:bookingid=>@booking.id ,:driverid=>@booking.driver_id})
    render :json => {
               :message => "Booking is canceled. ",
               :bookingId=>@booking.id
           }, :status => :created
  end

  def booking_params
    params.require(:booking).permit(:location, :driver_id, :status)
  end

end

taksi_server/app/views/bookings/edit.html.haml
%h1 Change data

= form_tag booking_path(@booking), :method => :put do

  = label :booking, :location, 'Location'
  = text_field :booking, 'location'

  = label :booking, :driver_id, 'Driver ID'
  = number_field :booking, 'driver_id'

  = label :booking, :status, 'Status'
  = select :booking, :status, ['Pending','Some other status', 'Another status']

  = submit_tag 'Update'

= link_to 'Back to bookings list', bookings_path

taksi_server/app/views/bookings/index.html.haml
-#  This file is app/views/bookings/index.html.haml
%h1 Bookings

%table#bookings
  %thead
    %tr
      %th Location
      %th Driver ID
      %th Status
  %tbody
    - @booking.each do |booking|
      %tr
        %td= booking.location
        %td= booking.driver_id
        %td= booking.status
        %td= link_to "View details #{booking.driver_id}", booking_path(booking)
        %td= link_to "Update data #{booking.driver_id}", edit_booking_path(booking)

taksi_server/app/views/bookings/show.html.haml
%h2 Details of driver with id #{@booking.driver_id} booking

%ul#details
  %li
    Location:
    = @booking.location

  %li
    Driver ID:
    = @booking.driver_id

  %li
    Current status:
    = @booking.status

= link_to 'Back to bookings list', bookings_path