taksi_server/config/routes.rb
Rails.application.routes.draw do
  match '*all' => 'application#cors_preflight', via: :options
  post "/bookings", :to => "bookings#create"
  post "/bookings/cancel", :to => "bookings#update"
  post "/drivers/request", :to=>"drivers#show"
  post "/drivers/answer", :to=>"drivers#answer"
  post "/drivers/accepted", :to=>"drivers#index"
  post "/drivers/requestStatus", :to=>"drivers#requestStatus"
  post "/drivers/updateStatus", :to=>"drivers#updateStatus"
  post "/drivers/location", :to=>"drivers#location"
  post "/drivers/invoice", :to=>"drivers#invoice"
  post "/drivers/invoicePayment", :to=>"drivers#invoicePay"
  post "/login", :to=>"drivers#login"

end

taksi_server/app/models/driver.rb
class Driver < ActiveRecord::Base
  has_many :bookings
  validates :username,  presence: true, length: { maximum: 50 }
  validates :password,  presence: true
  
  def self.authenticate(username, password)
    driver = find_by_username(username)
    if driver && driver.password == password
      driver
    else
      nil
    end
  end
end

taksi_server/app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    booking=Booking.where(:driver_id=>params["driver"]["id"],:status=>'active').first

    if(booking)
      address=booking.location
      l=locationParse(address)
      location=Geocoder.address(l)
      render :json => {:haveBooking=> true,
                     :beginning => location,
                     :destination=>booking.destination,
                     :bookingid=>booking.id ,
                     :fee=>booking.fee
           }, :status => :created
    else
        render :json => {:haveBooking=> false, :message => "you don't have active booking"}, :status => :created
    end

  end

  def edit
    @driver = Driver.find params[:id]
  end
  #shows bookings of the driver
  def show
    booking=Booking.where(:driver_id=>params["driver"]["id"],:status=>'pending').first
    if(booking!=nil)
      address=booking.location
      l=locationParse(address)
      location=Geocoder.address(l)
      driver=Driver.find(params["driver"]["id"])
      driverLoc=locationParse(driver.location)
      render :json => {:haveBooking=> true,
                       :location => location,
                       :destination=>booking.destination,
                       :bookingid=>booking.id ,:driverid=>params["driver"]["id"],
                       :lat =>l[0], :lng=>l[1],
                       :myLat=>driverLoc[0],:myLng=>driverLoc[1],
                       :fee=>booking.fee
             }, :status => :created
    else
      render :json => {:haveBooking=> false, :message => "You don't have booking requests"}, :status => :created
    end

  end

  #detects answer to the booking from driver
  def answer
    message=''
    booking=Booking.find(params["bookingid"])
    if (params["answer"]=='finished')
      booking.status='finished'
      booking.save!
      driver=driverUpdate(booking.driver_id,"Available",DateTime.now)
      Pusher.trigger('bookings', 'async_notification', { delivered:true, bookingId:booking.id })
      message="Good Job. You succesfully delivered customer"
    elsif(params["answer"]=='ignored')
      driver=Driver.find(booking.driver_id)

      if(driver.status=='Busy' && booking.status=='pending')
        driver=driverUpdate(booking.driver_id,"Available",DateTime.now)
        #new driver search
        arg=locationParse(booking.location)
        BookingsAsyncJob.new.async.assignToDriver(booking, arg[0],arg[1])
        message="Cancelation is done"
      end
    elsif(params["answer"])

      booking.status="active"
      booking.save!
      message="Customer is waiting"
      Pusher.trigger('bookings', 'async_notification', { message: "#{params[:duration]}", bookingId:booking.id , pusherTrue:true})
    else
      driver=driverUpdate(booking.driver_id,"Available",DateTime.now)
      #new driver search
      arg=locationParse(booking.location)
      BookingsAsyncJob.new.async.assignToDriver(booking, arg[0],arg[1])
      message="Cancelation is done"
    end
    render :json => {:message => message}, :status => :created
  end

  def update
    @driver = Driver.find params[:id]
    @driver.update_attributes!(driver_params)
    redirect_to drivers_path
  end

  def driver_params
    params.require(:driver).permit(:username, :password, :status)
  end

  def login
    driver = Driver.authenticate(params[:username], params[:password])
    if driver
      session[:user_id] = driver.id
      render :json => {:message => "Logged in", :isLogin => true, :userId => session[:user_id]}
    else
      render :json => {:message => "Error", :isLogin => false, :user_id => session[:user_id]}
    end

  end

  def invoice
    bookings=Booking.where(:driver_id=>params["driver"]["id"],:status=>'finished',:created_at=> Date.today.beginning_of_month..Date.today.end_of_month,:paid=>false)
    #Booking.where(:driver_id=>params["driver"]["id"],:status=>'finished',:created_at=>30.days.ago..Time.now)
    total= ( Booking.where(:status=>'finished',:driver_id=>params["driver"]["id"],:created_at=> Date.today.beginning_of_month..Date.today.end_of_month,:paid=>false).sum :fee)
    yesPayment=false
    if(bookings.count>0)
      yesPayment=true
    end
    charged=(total*0.03).round(2)
    render :json => {:total => total, :bookings => bookings,:charged=>charged,:yesPayment=>yesPayment}
  end


  def invoicePay
    bookings=Booking.where(:driver_id=>params["driver"]["id"],:status=>'finished',:created_at=> Date.today.beginning_of_month..Date.today.end_of_month,:paid=>false).update_all(:paid=>true)
    render :json => {:paid => true, :driverId => params["driver"]["id"]}
  end

  def location
    #{"lat"=>58.3767894, "long"=>26.720647099999997, "driverId"=>"12", "controller"=>"drivers", "action"=>"location", "driver"=>{}}
    driver = Driver.find(params[:driverId]);
    driver.location="{\"lat\" : #{params[:lat]},\"lng\" : #{params[:long]}}";
    driver.save!
    render :json => {:message => "location updated"}
  end

  def requestStatus
    driver = Driver.find(params[:id]);
    render :json => {:message => 'Driver status request', :driverStatus => driver.status}
  end

  def updateStatus
    driver = Driver.find(params[:id])
    driver.status = params[:driverStatus]
    driver.save!
    render :json => {:message => 'Driver status successfully updated'}
  end

end

taksi_server/app/helpers/drivers_helper.rb
module DriversHelper
end

taksi_server/app/views/drivers/edit.html.haml
%h1 Change data

= form_tag driver_path(@driver), :method => :put do

  = label :driver, :username, 'Username'
  = text_field :driver, 'username'

  = label :driver, :password, 'Password'
  = text_field :driver, 'password'

  = label :driver, :status, 'Status'
  = select :driver, :status, ['Available','Busy', 'Off-duty', 'Invisible']

  = submit_tag 'Update'

= link_to 'Back to drivers list', drivers_path

taksi_server/app/views/drivers/index.html.haml
%h1 Drivers

%table#drivers

  %thead
    %tr
      %th Username
      %th Password
      %th Status
      %th Update details

  %tbody
    - @driver.each do |driver|
      %tr
        %td= driver.username
        %td= driver.password
        %td= driver.status
        %td= link_to "View details #{driver.username}", driver_path(driver)
        %td= link_to 'Update data', edit_driver_path(driver)

  -#select_tag :new_status, options_for_select(['1','2','3'])
  -#= button_to 'Update', {:controller => "drivers", :action => "update", :method => :post}

taksi_server/app/views/drivers/login.html.erb
<h1>Log in</h1>

<%= form_tag "/login" do %>
  <p>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </p>
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  <p class="button"><%= submit_tag "Log in" %></p>
<% end %>

taksi_server/app/views/drivers/show.html.haml
%h2 Details of #{@driver.username}

%ul#details
  %li
    Username:
    = @driver.username

  %li
    Password:
    = @driver.password

  %li
    Current status:
    = @driver.status

= link_to 'Back to drivers list', drivers_path